runtime: python39
api_version: 1
threadsafe: yes
instance_class: B1
default_expiration: "4d 5h"
entrypoint: gunicorn -b :$PORT app:app

service: youtube-scraper-app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

handlers:
- url: .*
  script: auto
  secure: always
  http_headers:
    Access-Control-Allow-Origin: https://youtube-scraper-app.uc.r.appspot.com

